# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tfgg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/VivadoProject/soc/soc.cache/wt [current_project]
set_property parent.project_path F:/VivadoProject/soc/soc.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_ip F:/VivadoProject/soc/soc.srcs/sources_1/ip/inst_rom/inst_rom.xci
set_property used_in_implementation false [get_files -all f:/VivadoProject/soc/soc.srcs/sources_1/ip/inst_rom/inst_rom.dcp]
set_property is_locked true [get_files F:/VivadoProject/soc/soc.srcs/sources_1/ip/inst_rom/inst_rom.xci]

synth_design -top inst_rom -part xc7a100tfgg484-1 -mode out_of_context
rename_ref -prefix_all inst_rom_
write_checkpoint -noxdef inst_rom.dcp
catch { report_utilization -file inst_rom_utilization_synth.rpt -pb inst_rom_utilization_synth.pb }
if { [catch {
  file copy -force F:/VivadoProject/soc/soc.runs/inst_rom_synth_1/inst_rom.dcp F:/VivadoProject/soc/soc.srcs/sources_1/ip/inst_rom/inst_rom.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub F:/VivadoProject/soc/soc.srcs/sources_1/ip/inst_rom/inst_rom_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub F:/VivadoProject/soc/soc.srcs/sources_1/ip/inst_rom/inst_rom_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim F:/VivadoProject/soc/soc.srcs/sources_1/ip/inst_rom/inst_rom_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim F:/VivadoProject/soc/soc.srcs/sources_1/ip/inst_rom/inst_rom_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir F:/VivadoProject/soc/soc.ip_user_files/ip/inst_rom]} {
  catch { 
    file copy -force F:/VivadoProject/soc/soc.srcs/sources_1/ip/inst_rom/inst_rom_stub.v F:/VivadoProject/soc/soc.ip_user_files/ip/inst_rom
  }
}

if {[file isdir F:/VivadoProject/soc/soc.ip_user_files/ip/inst_rom]} {
  catch { 
    file copy -force F:/VivadoProject/soc/soc.srcs/sources_1/ip/inst_rom/inst_rom_stub.vhdl F:/VivadoProject/soc/soc.ip_user_files/ip/inst_rom
  }
}
