# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tfgg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/VivadoProject/soc/soc.cache/wt [current_project]
set_property parent.project_path F:/VivadoProject/soc/soc.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files F:/VivadoProject/soc/soc.srcs/io_temp.coe
add_files F:/VivadoProject/soc/soc.srcs/fp_mem.coe
add_files -quiet F:/VivadoProject/soc/soc.runs/inst_rom_synth_1/inst_rom.dcp
set_property used_in_implementation false [get_files F:/VivadoProject/soc/soc.runs/inst_rom_synth_1/inst_rom.dcp]
add_files -quiet F:/VivadoProject/soc/soc.runs/data_mem_synth_1/data_mem.dcp
set_property used_in_implementation false [get_files F:/VivadoProject/soc/soc.runs/data_mem_synth_1/data_mem.dcp]
read_verilog -library xil_defaultlib {
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/g_p.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/add.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/cla_2.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/cla_4.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/cla_8.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/cla_16.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/cla_32.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/add1.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/wallace_tree26x24_unsigned_partial.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/mux2x32.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/cla32.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/wallace_tree28x24_unsigned.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/wallace_tree26_unsigned.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/wallace_tree26x24_unsigned.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/wallace_tree24_unsigned_partial.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/shift_mux.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/addsub32.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/shift_to_msb_equ_1.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/shift_even_bits.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/root_newton24.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/reg_mul_add.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/reg_e123.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/reg_cal_norm.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/reg_align_cal.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/reg_add_norm.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/pipeimem.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/newton24.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/mux4x32.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/fsqrt_reg_e123.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/fmul_norm.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/fmul_mul.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/fadd_norm.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/fadd_cal.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/fadd_align.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/dffe32.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/alu.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/imports/new/DISP.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/regfile2w.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/regfile.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/pipepc.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/pipemwreg.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/pipemem.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/pipeir.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/pipeif.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/pipeidcu.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/pipeexe.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/pipeemreg.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/pipedereg.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/mux2x5.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/imports/new/ioread.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/imports/new/IO.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/fsqrt_newton.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/fmul.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/fdiv_newton.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/fadder.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/imports/new/clock_div.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/iu.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/imports/new/IOCtrl.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/sources_1/new/fpu.v
  F:/VivadoProject/soc/soc.srcs/sources_1/imports/Desktop/top_design.v
}
read_xdc F:/VivadoProject/soc/soc.srcs/constrs_1/new/DISP.xdc
set_property used_in_implementation false [get_files F:/VivadoProject/soc/soc.srcs/constrs_1/new/DISP.xdc]

synth_design -top top_design -part xc7a100tfgg484-1
write_checkpoint -noxdef top_design.dcp
catch { report_utilization -file top_design_utilization_synth.rpt -pb top_design_utilization_synth.pb }
